export const SHOW_HIDDEN_MENU = "SHOW_HIDDEN_MENU";
export const COLOR_MENU_ITEM = "COLOR_MENU_ITEM";

export const GET_BOATS_CARDS_LIST = "GET_BOATS_CARDS_LIST";
export const GET_BOAT_CARD_INFO = "GET_BOAT_CARD_INFO";
export const CLEAR_BOAT_CARD_INFO = "CLEAR_BOAT_CARD_INFO";
