export const GET_LOGIN_TOKEN = "GET_LOGIN_TOKEN";

export const SET_SEARCH_PARAMS_BOATS = "SET_SEARCH_PARAMS";
export const GET_BOATS_CARDS_LIST = "GET_BOATS_CARDS_LIST";
export const GET_BOAT_CARD_INFO = "GET_BOAT_CARD_INFO";
export const CLEAR_BOAT_CARD_INFO = "CLEAR_BOAT_CARD_INFO";

// export const SET_SEARCH_PARAMS_BOATS = "SET_SEARCH_PARAMS_BOATS";
export const GET_DATA_BY_SEARCH_PARAMS_BOAT = "GET_DATA_BY_SEARCH_PARAMS_BOAT";

export const GET_DATA_BY_SEARCH_PARAMS_LICENSE = "GET_DATA_BY_SEARCH_PARAMS_LICENSE";
export const GET_LICENSE_BY_ID = "GET_LICENSE_BY_ID";
export const SET_SEARCH_PARAMS_LICENSE = "SET_SEARCH_PARAMS_LICENSE";
export const SET_SEARCH_PARAMS_BOATS_REG = "SET_SEARCH_PARAMS_BOATS_REG";
export const SET_SEARCH_PARAMS_REG_INFORM_CHANGES = "SET_SEARCH_PARAMS_REG_INFORM_CHANGES";
export const GET_DATA_BY_SEARCH_PARAMS_BOATS_REG = "GET_DATA_BY_SEARCH_PARAMS_BOATS_REG";

export const GET_DATA_BY_SEARCH_PARAMS_BASES_BUILDING = "GET_DATA_BY_SEARCH_PARAMS_BASES_BUILDING";
export const SET_SEARCH_PARAMS_BASES_BUILDING = "SET_SEARCH_PARAMS_BASES_BUILDING";
export const ADD_NEW_BASES = "ADD_NEW_BASES";
export const EDIT_BASES = "EDIT_BASES";

export const GET_DICTIONARY_GIMS_SECTIONS = "GET_DICTIONARY_GIMS_SECTIONS";
export const GET_DICTIONARY_OWNER_TYPE = "GET_DICTIONARY_OWNER_TYPE";
export const GET_DICTIONARY_NSI_CHECK_STATUS = "GET_DICTIONARY_NSI_CHECK_STATUS";
export const GET_DICTIONARY_RAYON_FOR_OBL = "GET_DICTIONARY_RAYON_FOR_OBL";

export const ADD_NEW_SPEC_MARK = "ADD_NEW_SPEC_MARK";
export const ADD_NEW_CONF_MARK = "ADD_NEW_CONF_MARK";
export const REVOKE_LICENSE = "REVOKE_LICENSE";

export const GET_USERS_LIBRARY = "GET_USERS_LIBRARY";
export const GET_ATE_LIBRARY = "GET_ATE_LIBRARY";
export const GET_APP_REG_STATUS_LIBRARY = "GET_APP_REG_STATUS_LIBRARY";

export const ADD_NEW_BOAT_INFO = "ADD_NEW_BOAT_INFO";
export const EDIT_BOAT_INFO = "EDIT_BOAT_INFO";

export const GET_BOATS_REG_INFO = "GET_BOATS_REG_INFO";
export const GET_BOATS_DECISION_INFO = "GET_BOATS_DECISION_INFO";

export const SET_SORT_STATE_TABLE = "SET_SORT_STATE_TABLE";

export const GET_REG_INFORM_CHANGES = "GET_REG_INFORM_CHANGES";
export const SET_SEARCH_PARAMS_BOATS_ADMIN_PROC = "SET_SEARCH_PARAMS_BOATS_ADMIN_PROC";
export const GET_REG_INFORM_CHANGES_BOAT_CARDS = "GET_REG_INFORM_CHANGES_BOAT_CARDS";

export const ADD_NEW_ENGINE_CHECK = "ADD_NEW_ENGINE_CHECK";
export const ADD_NEW_SPEC_MARK_APP = "ADD_NEW_SPEC_MARK_APP";
export const DELETE_NEW_NOTE_APP = "DELETE_NEW_NOTE_APP";
export const ADD_NEW_DEAL = "ADD_NEW_DEAL";
export const ADD_NEW_STATEMENT_DATA = "ADD_NEW_STATEMENT_DATA";
export const SET_DATA_FOR_STATEMENT_TABLES = "SET_DATA_FOR_STATEMENT_TABLES";
export const ADD_NEW_STATEMENT = "ADD_NEW_STATEMENT";
export const CLEAR_NEW_STATEMENT = "CLEAR_NEW_STATEMENT";
export const CLEAR_DECISION_DATA = "CLEAR_DECISION_DATA";

export const SET_SEARCH_PARAMS_DUP_SHIP_TICKET = "SET_SEARCH_PARAMS_DUP_SHIP_TICKET";
export const SET_SEARCH_PARAMS_BOATS_DUP_SHIP_TICKET = "SET_SEARCH_PARAMS_BOATS_DUP_SHIP_TICKET";
export const GET_DUP_SHIP_TICKET_INFO = "GET_DUP_SHIP_TICKET_INFO";
export const GET_BOAT_CARD_FOR_DUPLICATE = "GET_BOAT_CARD_FOR_DUPLICATE";
export const ADD_DATA_FOR_DUPLICATE = "ADD_DATA_FOR_DUPLICATE";
export const GET_DUPLICATE_DECISION_INFO = "GET_DUPLICATE_DECISION_INFO";
// export const GET_DUP_SHIP_TICKET_BOAT_CARDS = "GET_DUP_SHIP_TICKET_BOAT_CARDS";

export const SET_SEARCH_PARAMS_SHIPS_TICKET = "SET_SEARCH_PARAMS_SHIPS_TICKET";
export const GET_SHIPS_TICKET_INFO = "GET_SHIPS_TICKET_INFO";
export const GET_SHIPS_TICKET_DECISION_INFO = "GET_SHIPS_TICKET_DECISION_INFO";

export const SET_SEARCH_PARAMS_PROVISION_INFORMATION = "SET_SEARCH_PARAMS_PROVISION_INFORMATION";
export const GET_DATA_BY_PARAMS_PROVISION_INFORMATION = "GET_DATA_BY_PARAMS_PROVISION_INFORMATION";

export const SET_SEARCH_PARAMS_TRANSPORT_ACCIDENTS = "SET_SEARCH_PARAMS_TRANSPORT_ACCIDENTS";
export const GET_DATA_BY_SEARCH_PARAMS_TRANSPORT_ACCIDENTS = "GET_DATA_BY_SEARCH_PARAMS_TRANSPORT_ACCIDENTS";
export const ADD_NEW_CULPRIT = "ADD_NEW_CULPRIT";
export const ADD_NEW_INJURED = "ADD_NEW_INJURED";
export const DELETE_NEW_NOTE_ACCIDENT = "DELETE_NEW_NOTE_ACCIDENT";
export const ADD_NEW_ACCIDENT_DATA = "ADD_NEW_ACCIDENT_DATA";
export const CLEAR_ACCIDENT_DATA = "CLEAR_ACCIDENT_DATA";
export const GET_BOAT_INFO_BY_REGNUM = "GET_BOAT_INFO_BY_REGNUM";
export const GET_TRANSPORT_ACCIDENT_INFO = "GET_TRANSPORT_ACCIDENT_INFO";
export const SAVE_TRANSPORT_ACCIDENT_MAIN_INFO = "SAVE_TRANSPORT_ACCIDENT_MAIN_INFO";
export const DELETE_ACCIDENT_FILE = "DELETE_ACCIDENT_FILE";

export const SET_SEARCH_PARAMS_TECH_EXAM = "SET_SEARCH_PARAMS_TECH_EXAM";
export const GET_DATA_BY_SEARCH_PARAMS_TECH_EXAM = "GET_DATA_BY_SEARCH_PARAMS_TECH_EXAM";
export const SET_SEARCH_PARAMS_BOATS_TECH_EXAM = "SET_SEARCH_PARAMS_BOATS_TECH_EXAM";
export const GET_TECH_EXAM_CHANGES_BOAT_CARDS = "GET_TECH_EXAM_CHANGES_BOAT_CARDS";
