export const fieldBoatOptions = {
  boatVin: {
    key: "boatVin",
    value: "Заводской\n" + "(идентификационный) номер",
    type: "text",
    defaultValue: null,
    readOnly: false,
    disabled: false,
    required: true,
    maxlength: 15,
  },
  parkingPlace: {
    key: "parkingPlace",
    value: "Место стоянки",
    type: "text",
    defaultValue: null,
    readOnly: false,
    disabled: false,
    required: true,
  },
  boatType: {
    key: "boatType",
    value: "Тип",
    type: "selectSearch",
    defaultValue: null,
    readOnly: false,
    options: [],
    disabled: false,
    required: true,
  },
  boatVid: {
    key: "boatVid",
    value: "Вид",
    type: "selectSearch",
    defaultValue: null,
    readOnly: false,
    options: [],
    disabled: false,
    required: true,
  },
  bodyMaterial: {
    key: "bodyMaterial",
    value: "Материал корпуса",
    type: "selectSearch",
    defaultValue: null,
    readOnly: false,
    options: [],
    disabled: false,
    required: true,
  },
  boatPayload: {
    key: "boatPayload",
    value: "Грузоподъемность (кг)",
    type: "text",
    defaultValue: null,
    readOnly: false,
    disabled: false,
    required: true,
  },
  engpwrmax: {
    key: "engpwrmax",
    value: "Предельная мощность двигателей, л.с.",
    type: "text",
    defaultValue: null,
    readOnly: false,
    disabled: false,
  },
  boatYear: {
    key: "boatYear",
    value: "Год постройки",
    type: "text",
    defaultValue: null,
    readOnly: false,
    disabled: false,
    required: true,
  },
  engineNum: {
    key: "engineNum",
    value: "Количество двигателей",
    type: "text",
    defaultValue: null,
    readOnly: false,
    disabled: false,
  },
  boatName: {
    key: "boatName",
    value: "Название (при наличии)",
    type: "text",
    defaultValue: null,
    readOnly: false,
    disabled: false,
  },
  boatLength: {
    key: "boatLength",
    value: "Длина (м)",
    type: "text",
    defaultValue: null,
    readOnly: false,
    disabled: false,
    required: true,
  },
  boatWidth: {
    key: "boatWidth",
    value: "Ширина(м)",
    type: "text",
    defaultValue: null,
    readOnly: false,
    disabled: false,
    required: true,
  },
  boatHeight: {
    key: "boatHeight",
    value: "Высота (м)",
    type: "text",
    defaultValue: null,
    readOnly: false,
    disabled: false,
    required: true,
  },
  passengersNum: {
    key: "passengersNum",
    value: "Пассажировместимость (чел.)",
    type: "text",
    defaultValue: null,
    readOnly: false,
    disabled: false,
    required: true,
  },
  saCategory: {
    key: "saCategory",
    value: "Категория сложности района плавания",
    type: "selectSearch",
    defaultValue: null,
    options: [],
    readOnly: false,
    disabled: false,
    required: true,
  },
};

export function setOptionsForBoat(types, kinds, materials, saCategory) {
  fieldBoatOptions.boatType.options = types;
  fieldBoatOptions.boatVid.options = kinds;
  fieldBoatOptions.bodyMaterial.options = materials;
  fieldBoatOptions.saCategory.options = saCategory;
  return fieldBoatOptions;
}
